name: Preparant per producci贸
run-name: ${{ github.actor }} est pujant l'aplicaci贸 a PROD 
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Instal路lar depend猫ncies i construir el projecte Vue
        run: |
          cd vue/vue-project
          npm ci
          npm run build

      - name: Ejecutar ESLint en el c贸digo
        run: |
          cd vue/vue-project
          npm run lint

      - name: SCP a producci贸
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" vue/vue-project/dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a22poldonpoz/web/actionspol.daw.inspedralbes.cat/public_html/
